apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
data:
  NAME: YXBwX2Ri
  USER: YXBwX3VzZXI=
  PASSWORD: MTIzNA==
  HOST: bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbA==